"""Chemistry logic over the curated tables.

Every function here is a *decision* the tables in `chem.data` support -- is this
oxide acidic, does this salt precipitate, does this metal displace that one.
Rules may read data; data never reads rules.

Three kinds of module:

- lookups over one table: `elements`, `ions`, `activity`, `solubility`, `oxides`
- reaction templates: `acids`, `bases`, `salts`, `ammonia`, `reduction`,
  `unstable`
- `species` (what class a formula belongs to) and `reactions` (the dispatcher
  that asks every template what one or two species can do)

Balancing is *not* here. It is a separate pass over the finished reactions, in
`chem.balance`, and it is the only place ChemPy is used.
"""

from chem.rules.acids import (
    DISPLACEMENT,
    HYDRATION,
    HYDROGENATION,
    INSOLUBLE_ACIDS,
    acid_formula,
    acid_of,
    as_acid,
    decomposition_of,
    displace_from_salt,
    hydrate,
    hydrogenate,
    is_acid,
    is_stronger,
    proton_count,
    routes_to,
    strength_of,
)
from chem.rules.ammonia import (
    DISSOLUTION,
    HYDRIDE_WITH_ACID,
    LIBERATION,
    as_hydride,
    dissolve,
    hydride_of,
    is_hydride,
    liberate,
    routes_to_ammonia,
    synthesise,
    with_acid,
)
from chem.rules.activity import (
    displaces_hydrogen_from_acid,
    in_series,
    is_more_active,
    reacts_with_cold_water,
    water_reactivity,
)
from chem.rules.bases import (
    METAL_WITH_WATER,
    OXIDE_HYDRATION,
    as_base,
    base_decomposition,
    base_formula,
    base_of,
    base_strength,
    hydrate_oxide,
    is_base,
    is_stronger_base,
    metal_with_water,
    routes_to_base,
)
from chem.rules.elements import (
    has_amphoteric_oxide,
    is_curated,
    is_metal,
    is_metalloid,
    is_nonmetal,
    is_reactive,
)
from chem.rules.ions import (
    charge_of,
    default_anion_charge,
    default_cation_charge,
    ion_name,
    is_anion,
    is_cation,
)
from chem.rules.oxides import (
    OXIDATION,
    anhydride,
    anhydride_of,
    hydrates,
    is_acidic_oxide,
    oxidations,
    oxide_character,
)
from chem.rules.catalogue import RULE_SLUGS, rule_slug
from chem.rules.commonness import all_common, is_common
from chem.rules.chromate import ACIDIFY, ALKALISE, CHROMATE, DICHROMATE, acidify, alkalise
from chem.rules.display import (
    Species,
    anion_name,
    cation_name,
    class_name,
    constituent_ions,
    display_name,
    species_record,
    state_of,
)
from chem.rules.reactions import combine, decompose, products_of
from chem.rules.reduction import (
    ALUMINOTHERMIC,
    REDUCTION,
    as_reducer,
    is_reducer,
    metal_with_oxide,
    reduce_oxide,
    routes_to_element,
)
from chem.rules.salts import (
    ACID_SALT_NEUTRALISATION,
    ACID_SALT_WITH_BASE,
    ACID_WITH_OXIDE,
    BASE_WITH_OXIDE,
    CARBONATE_DECOMPOSITION,
    DOUBLE_DISPLACEMENT,
    HALOGEN_DISPLACEMENT,
    HYDROGENCARBONATE_DECOMPOSITION,
    METAL_WITH_ACID,
    SALT_WITH_PARENT_ACID,
    acid_salt_with_base,
    decompose_hydrogencarbonate,
    partial_neutralise,
    salt_with_parent_acid,
    METAL_WITH_SALT,
    NEUTRALISATION,
    OXIDE_WITH_OXIDE,
    SYNTHESIS,
    acid_with_basic_oxide,
    base_with_acidic_oxide,
    cation_charge_for,
    decompose_carbonate,
    double_displacement,
    halogen_with_salt,
    hydroxide_formula,
    ions_of,
    is_salt,
    metal_with_acid,
    metal_with_nonmetal,
    metal_with_salt,
    neutralise,
    oxide_of_cation,
    oxide_with_oxide,
    salt_formula,
)
from chem.rules.solubility import certainly_precipitates, precipitates, solubility
from chem.rules.species import SpeciesClass, classify, is_known
from chem.rules.unstable import (
    DECOMPOSITION,
    decompose_unstable,
    decomposition_products,
    is_unstable,
)

__all__ = [
    "ACIDIFY",
    "ACID_SALT_NEUTRALISATION",
    "ACID_SALT_WITH_BASE",
    "ACID_WITH_OXIDE",
    "ALKALISE",
    "ALUMINOTHERMIC",
    "BASE_WITH_OXIDE",
    "CARBONATE_DECOMPOSITION",
    "CHROMATE",
    "DECOMPOSITION",
    "DICHROMATE",
    "DISPLACEMENT",
    "DISSOLUTION",
    "DOUBLE_DISPLACEMENT",
    "HALOGEN_DISPLACEMENT",
    "HYDRATION",
    "HYDROGENCARBONATE_DECOMPOSITION",
    "HYDROGENATION",
    "HYDRIDE_WITH_ACID",
    "INSOLUBLE_ACIDS",
    "LIBERATION",
    "METAL_WITH_ACID",
    "METAL_WITH_SALT",
    "METAL_WITH_WATER",
    "NEUTRALISATION",
    "OXIDATION",
    "OXIDE_HYDRATION",
    "OXIDE_WITH_OXIDE",
    "REDUCTION",
    "RULE_SLUGS",
    "SALT_WITH_PARENT_ACID",
    "SYNTHESIS",
    "Species",
    "SpeciesClass",
    "acid_formula",
    "acid_of",
    "acid_salt_with_base",
    "acid_with_basic_oxide",
    "acidify",
    "alkalise",
    "all_common",
    "anhydride",
    "anhydride_of",
    "anion_name",
    "as_acid",
    "as_base",
    "as_hydride",
    "as_reducer",
    "base_decomposition",
    "base_formula",
    "base_of",
    "base_strength",
    "base_with_acidic_oxide",
    "cation_charge_for",
    "cation_name",
    "certainly_precipitates",
    "charge_of",
    "class_name",
    "classify",
    "combine",
    "constituent_ions",
    "decompose",
    "decompose_carbonate",
    "decompose_hydrogencarbonate",
    "decompose_unstable",
    "decomposition_of",
    "decomposition_products",
    "default_anion_charge",
    "default_cation_charge",
    "displace_from_salt",
    "display_name",
    "displaces_hydrogen_from_acid",
    "dissolve",
    "double_displacement",
    "halogen_with_salt",
    "has_amphoteric_oxide",
    "hydrate",
    "hydrate_oxide",
    "hydrates",
    "hydride_of",
    "hydrogenate",
    "hydroxide_formula",
    "in_series",
    "ion_name",
    "ions_of",
    "is_acid",
    "is_acidic_oxide",
    "is_anion",
    "is_base",
    "is_cation",
    "is_common",
    "is_curated",
    "is_hydride",
    "is_known",
    "is_metal",
    "is_metalloid",
    "is_more_active",
    "is_nonmetal",
    "is_reactive",
    "is_reducer",
    "is_salt",
    "is_stronger",
    "is_stronger_base",
    "is_unstable",
    "liberate",
    "metal_with_acid",
    "metal_with_nonmetal",
    "metal_with_oxide",
    "metal_with_salt",
    "metal_with_water",
    "neutralise",
    "oxidations",
    "oxide_character",
    "oxide_of_cation",
    "oxide_with_oxide",
    "partial_neutralise",
    "precipitates",
    "products_of",
    "proton_count",
    "reacts_with_cold_water",
    "reduce_oxide",
    "routes_to",
    "routes_to_ammonia",
    "routes_to_base",
    "routes_to_element",
    "rule_slug",
    "salt_formula",
    "salt_with_parent_acid",
    "solubility",
    "species_record",
    "state_of",
    "strength_of",
    "synthesise",
    "water_reactivity",
    "with_acid",
]
